
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module MAC(


	input 	signed	   		  [7:0]		inA,
	input 	signed	    		  [7:0]		inB,
	input				  								clk,
	input 							  	 macc_clear,
	output reg	signed	     [18:0]		macc_out

);





always @(posedge clk) begin


		if (macc_clear == 1) begin
			macc_out <= inA * inB;
			end

		else begin
			macc_out <= macc_out + (inA * inB);
			end
	
end



endmodule
